Feature/39 message api
Wingle-SMWU/Wingle-Frontend pull request #51
Opened 2023-04-29 01:39 UTC by yeonkr

## PR 내용
- message API 연결

## branch
- [ ] feat -> develop
- [ ] develop -> main

## 리뷰

2023-04-30 09:03 UTC, JudithHopps approved these changes

2023-04-30 09:03 UTC, JudithHopps commented on src/pages/messages/index.tsx
> +            console.log(list)
CONSOLE.LOG 지우는 게 좋을것 ㄱ같아요

2023-04-30 09:03 UTC, JudithHopps commented on public/images/message/profiledefault.png
message 밖에 빼주세요

2023-04-30 09:06 UTC, JudithHopps requested changes

2023-04-30 09:06 UTC, JudithHopps commented on src/atoms/temp.ts
새로 파일 작성해서 따로 atom 파일 작성해주세요!
타입도 지정 부탁드려요!

2023-04-30 12:31 UTC, yxunakim84 commented on src/hooks/message/useGetMessage.ts
> +      setRoomList(item.data);
1. data 를 가져오는 부분에서 item.data로 한번 더 처리해주고 있는데 messageApi.ts 의 api 호출 함수에서 데이터를 바로 리턴해주면 여기 파일에서는 item.data로 안 하고 바로 data 로 사용할 수 있어서 보기에 더 좋을 것 같아요~
src/api/message/messageApi.ts 파일에 있는 api 호출 함수에서 const {data: response} = await ~~~ return response.data 로 고쳐주면 data만 바로 리턴해줄 수 있습니다!

2023-04-30 12:33 UTC, yxunakim84 commented on src/hooks/message/useGetMessage.ts
> +      item.data?.map(((message:Message) => {
2. useQuery로 받아온 데이터 타입을 지정해주지 않아서 타입이 any로 뜨고 있어요! 그리고 map함수 돌리는 부분에서 message의 타입을 지정해주고 있는데, useQuery로 받아온 뒤에 타입을 지정해주는 것보다 queryfn으로 사용해주는 함수 자체에서 return 타입을 지정해줘서 보내주는게 더 나은 방법인 걸로 알고 있습니다!
그래서 src/api/message/messageApi.ts 파일에 있는 api 호출 함수에서 리턴 타입을 지정해주는게 좋을 것 같아요. 위에 말씀드린 부분까지 하면 최종적으로

export const getMessage = async (roomId: number, page: number , size: number ): Promise<Message[]> => {
  const { data: response } = await instance.get<GetMessageResponse>(`/messages/${roomId}?page=${0}&size=${1000}`);
  return response.data;
};
이렇게 수정하면 어떨지 제안드려봅니다! (getMessageRoom api 함수도 마찬가지로 하면 좋을 것 같아요)

2023-04-30 13:44 UTC, yxunakim84 commented on src/utils/betweenTime.ts
> +}
여기 betweenTime.ts 파일이랑 convertDate.ts 파일이 머지 컨플릭트 날 텐데 betweenTime.ts는 제가 작성한 버전으로 해주시고 convertDate.ts는 연주님이 쓰신거랑 동일하게 바꿔놨는데 아마 공백 때문에 다르다고 표시되는 것 같아서 아무거나 편하신대로 해주시면 될 것 같습니다!! 😀

2023-04-30 14:39 UTC, halmokme approved these changes
고생하셨습니다. 다른분들이 코멘트 해주신 부분 반영해주시면 더 깔끔한 코드를 작성할 수 있을 것 같습니다.

2023-05-01 07:03 UTC, yxunakim84 approved these changes

2023-05-01 11:12 UTC, rhino-ty approved these changes
고생하셨어요! 회의때랑 말씀해주신 부분들 수정해주세요 고생하셨습니다.

2023-05-01 14:07 UTC, yeonkr commented on public/images/message/profiledefault.png
이 부분은 머지 후에 빼기로 했어서 그대로 올렸습니다

2023-05-01 14:23 UTC, yeonkr commented on src/atoms/temp.ts
수정했습니다 감사합니다!

2023-05-01 14:36 UTC, yeonkr commented on src/hooks/message/useGetMessage.ts
> +      item.data?.map(((message:Message) => {
수정했습니다 꼼꼼한 확인 감사합니다!

2023-05-01 22:18 UTC, JudithHopps approved these changes

2023-05-01 22:24 UTC, merged